export const MBTI_KEYWORDS: Record<string, string[]> = {
  // Analysts
  INTJ: [
    'complex',
    'strategy',
    'psychological',
    'mystery',
    'intellectual',
    'mastermind',
    'chess',
    'planning',
    'brilliant',
    'calculated',
  ],
  INTP: [
    'logic',
    'theory',
    'experiment',
    'science',
    'analysis',
    'curious',
    'philosophical',
    'puzzle',
    'genius',
    'abstract',
  ],
  ENTJ: [
    'leadership',
    'commanding',
    'ambitious',
    'conquest',
    'power',
    'strategic',
    'empire',
    'dominant',
    'decisive',
    'visionary',
  ],
  ENTP: [
    'debate',
    'inventive',
    'clever',
    'witty',
    'challenging',
    'unconventional',
    'innovative',
    'creative',
    'quick-thinking',
    'versatile',
  ],

  // Diplomats
  INFJ: [
    'idealistic',
    'empathetic',
    'insightful',
    'meaningful',
    'deep',
    'prophetic',
    'compassionate',
    'inspiring',
    'visionary',
    'profound',
  ],
  INFP: [
    'romantic',
    'dreamer',
    'ideals',
    'emotional',
    'artistic',
    'gentle',
    'introspective',
    'poetic',
    'healing',
    'sensitive',
  ],
  ENFJ: [
    'charismatic',
    'inspiring',
    'mentor',
    'guidance',
    'heroic',
    'motivational',
    'diplomatic',
    'persuasive',
    'natural leader',
    'altruistic',
  ],
  ENFP: [
    'vibrant',
    'adventure',
    'friendship',
    'energetic',
    'creative',
    'spontaneous',
    'optimistic',
    'passionate',
    'enthusiastic',
    'imaginative',
  ],

  // Sentinels
  ISTJ: [
    'traditional',
    'order',
    'duty',
    'reliable',
    'structured',
    'methodical',
    'responsible',
    'disciplined',
    'practical',
    'meticulous',
  ],
  ISFJ: [
    'protective',
    'caring',
    'loyal',
    'devoted',
    'supportive',
    'nurturing',
    'tradition',
    'service',
    'conscientious',
    'warm',
  ],
  ESTJ: [
    'organized',
    'management',
    'authority',
    'efficiency',
    'direct',
    'administrator',
    'systematic',
    'honest',
    'dedicated',
    'strong-willed',
  ],
  ESFJ: [
    'social',
    'harmony',
    'helping',
    'community',
    'cooperative',
    'popular',
    'generous',
    'loyal',
    'sympathetic',
    'warm-hearted',
  ],

  // Explorers
  ISTP: [
    'mechanical',
    'technical',
    'hands-on',
    'cool',
    'resourceful',
    'practical',
    'craftsman',
    'problem-solver',
    'independent',
    'observant',
  ],
  ISFP: [
    'artistic',
    'aesthetic',
    'gentle',
    'nature',
    'peaceful',
    'creative',
    'charming',
    'flexible',
    'sensitive',
    'adventurous',
  ],
  ESTP: [
    'entertaining',
    'spontaneous',
    'action',
    'bold',
    'energetic',
    'thrill',
    'daring',
    'perceptive',
    'direct',
    'sociable',
  ],
  ESFP: [
    'fun',
    'entertaining',
    'spontaneous',
    'social',
    'lively',
    'performance',
    'enthusiastic',
    'playful',
    'outgoing',
    'exciting',
  ],
};
